// Copyright 2026 Travis Cunningham. Licensed under the Apache License, Version 2.0.

// Code generated by internal/gen. DO NOT EDIT.

//go:build !purego && (amd64 || arm64)

#include "textflag.h"

// foldK: entry i at offset 16*i is for distance d=16*(i+1) bytes: low qword K(8d+63), high qword K(8d-1).
DATA ·foldK+0(SB)/8, $0xeadc41fd2ba3d420 // d=16 K(191)
DATA ·foldK+8(SB)/8, $0x21e9761e252621ac // d=16 K(127)
DATA ·foldK+16(SB)/8, $0xb0bc2e589204f500 // d=32 K(319)
DATA ·foldK+24(SB)/8, $0xe1e0bb9d45d7a44c // d=32 K(255)
DATA ·foldK+32(SB)/8, $0xbdd7ac0ee1a4a0f0 // d=48 K(447)
DATA ·foldK+40(SB)/8, $0xa3ffdc1fe8e82a8b // d=48 K(383)
DATA ·foldK+48(SB)/8, $0x0c32cdb31e18a84a // d=64 K(575)
DATA ·foldK+56(SB)/8, $0x62242240ace5045a // d=64 K(511)
DATA ·foldK+64(SB)/8, $0x7b0ab10dd0f809fe // d=80 K(703)
DATA ·foldK+72(SB)/8, $0x03363823e6e791e5 // d=80 K(639)
DATA ·foldK+80(SB)/8, $0x3c255f5ebc414423 // d=96 K(831)
DATA ·foldK+88(SB)/8, $0x34f5a24e22d66e90 // d=96 K(767)
DATA ·foldK+96(SB)/8, $0xd083dd594d96319d // d=112 K(959)
DATA ·foldK+104(SB)/8, $0x946588403d4adcbc // d=112 K(895)
DATA ·foldK+112(SB)/8, $0xa1ca681e733f9c40 // d=128 K(1087)
DATA ·foldK+120(SB)/8, $0x5f852fb61e8d92dc // d=128 K(1023)
DATA ·foldK+128(SB)/8, $0xcd72351bf13cb8ca // d=144 K(1215)
DATA ·foldK+136(SB)/8, $0x3bee332187cc60f7 // d=144 K(1151)
DATA ·foldK+144(SB)/8, $0xb0fffabea073832e // d=160 K(1343)
DATA ·foldK+152(SB)/8, $0x66650420c4bfb826 // d=160 K(1279)
DATA ·foldK+160(SB)/8, $0xee25ff27102e240d // d=176 K(1471)
DATA ·foldK+168(SB)/8, $0xf62e65588693c72c // d=176 K(1407)
DATA ·foldK+176(SB)/8, $0x758ee09da263e275 // d=192 K(1599)
DATA ·foldK+184(SB)/8, $0x6d2d13de8038b4ca // d=192 K(1535)
DATA ·foldK+192(SB)/8, $0x3872b6300d5e5d6f // d=208 K(1727)
DATA ·foldK+200(SB)/8, $0xba7a3407e09207aa // d=208 K(1663)
DATA ·foldK+208(SB)/8, $0x3f2930bb5e9d61c5 // d=224 K(1855)
DATA ·foldK+216(SB)/8, $0x0d1476de2f12000f // d=224 K(1791)
DATA ·foldK+224(SB)/8, $0xeab05d4357a9b42f // d=240 K(1983)
DATA ·foldK+232(SB)/8, $0x224f0e5bd4980292 // d=240 K(1919)
DATA ·foldK+240(SB)/8, $0x37ccd3e14069cabc // d=256 K(2111)
DATA ·foldK+248(SB)/8, $0xa043808c0f782663 // d=256 K(2047)
DATA ·foldK+256(SB)/8, $0xf6865e6e09336523 // d=272 K(2239)
DATA ·foldK+264(SB)/8, $0xaf2157ca1ac6c761 // d=272 K(2175)
DATA ·foldK+272(SB)/8, $0x0091c92c3c944810 // d=288 K(2367)
DATA ·foldK+280(SB)/8, $0x5e44c93e98d82108 // d=288 K(2303)
DATA ·foldK+288(SB)/8, $0x38f659a9d21de14a // d=304 K(2495)
DATA ·foldK+296(SB)/8, $0xcd61588879b9fe22 // d=304 K(2431)
DATA ·foldK+304(SB)/8, $0x5b490ed66bc7198e // d=320 K(2623)
DATA ·foldK+312(SB)/8, $0x98a3c6207ae8373d // d=320 K(2559)
DATA ·foldK+320(SB)/8, $0xa4341ea70754fc16 // d=336 K(2751)
DATA ·foldK+328(SB)/8, $0x126dd5afb52f9ce4 // d=336 K(2687)
DATA ·foldK+336(SB)/8, $0xedf822c4d63c7728 // d=352 K(2879)
DATA ·foldK+344(SB)/8, $0xf03ca4363ad77178 // d=352 K(2815)
DATA ·foldK+352(SB)/8, $0xa0092bf548bf79d2 // d=368 K(3007)
DATA ·foldK+360(SB)/8, $0x215911d11dedbbd6 // d=368 K(2943)
DATA ·foldK+368(SB)/8, $0x6060c38d609f3e21 // d=384 K(3135)
DATA ·foldK+376(SB)/8, $0x5bdde9caef18f985 // d=384 K(3071)
DATA ·foldK+384(SB)/8, $0xb93e41242302a0d8 // d=400 K(3263)
DATA ·foldK+392(SB)/8, $0xb9d1ad02e7bdd4b0 // d=400 K(3199)
DATA ·foldK+400(SB)/8, $0xa654dc54e255bc86 // d=416 K(3391)
DATA ·foldK+408(SB)/8, $0x1c62cd4677a2190e // d=416 K(3327)
DATA ·foldK+416(SB)/8, $0xda36257a1d6c477e // d=432 K(3519)
DATA ·foldK+424(SB)/8, $0x593a983603eace9e // d=432 K(3455)
DATA ·foldK+432(SB)/8, $0x7e6341dda0383248 // d=448 K(3647)
DATA ·foldK+440(SB)/8, $0xb06a02f5c37fb81b // d=448 K(3583)
DATA ·foldK+448(SB)/8, $0x1f85eb5daa03dbb9 // d=464 K(3775)
DATA ·foldK+456(SB)/8, $0x6860ffa989545195 // d=464 K(3711)
DATA ·foldK+464(SB)/8, $0xaca27b938764b188 // d=480 K(3903)
DATA ·foldK+472(SB)/8, $0x24ea4e54779b35b9 // d=480 K(3839)
DATA ·foldK+480(SB)/8, $0x63fae1b85959c61f // d=496 K(4031)
DATA ·foldK+488(SB)/8, $0x4fc3a895085a0b72 // d=496 K(3967)
DATA ·foldK+496(SB)/8, $0xd0b3aa0ed6d54ae0 // d=512 K(4159)
DATA ·foldK+504(SB)/8, $0xc2409e2537aa5eb1 // d=512 K(4095)
GLOBL ·foldK(SB), RODATA|NOPTR, $512

// reduceK: K127 at +0, MU at +16, POLY at +32, each in the low qword with a zero high qword.
DATA ·reduceK+0(SB)/8, $0x21e9761e252621ac
DATA ·reduceK+8(SB)/8, $0
DATA ·reduceK+16(SB)/8, $0x27ecfa329aef9f77
DATA ·reduceK+24(SB)/8, $0
DATA ·reduceK+32(SB)/8, $0x34d926535897936b
DATA ·reduceK+40(SB)/8, $0
GLOBL ·reduceK(SB), RODATA|NOPTR, $48
