// Copyright 2026 Travis Cunningham. Licensed under the Apache License, Version 2.0.

// Code generated by internal/gen. DO NOT EDIT.

// Package kconst holds the carryless-multiply constants for CRC-64/NVME.
// K(e) = bitrev64(x^e mod P). Pairs[i] is for a fold distance of d = 16*(i+1)
// bytes: {K(8d+63), K(8d-1)}. MU and POLY are bitrev65(x^128 div P) and
// bitrev65(P) truncated to 64 bits.
package kconst

const (
	MU   uint64 = 0x27ecfa329aef9f77
	POLY uint64 = 0x34d926535897936b
	K127 uint64 = 0x21e9761e252621ac
)

var Pairs = [32][2]uint64{
	{0xeadc41fd2ba3d420, 0x21e9761e252621ac}, // d=16: K(191), K(127)
	{0xb0bc2e589204f500, 0xe1e0bb9d45d7a44c}, // d=32: K(319), K(255)
	{0xbdd7ac0ee1a4a0f0, 0xa3ffdc1fe8e82a8b}, // d=48: K(447), K(383)
	{0x0c32cdb31e18a84a, 0x62242240ace5045a}, // d=64: K(575), K(511)
	{0x7b0ab10dd0f809fe, 0x03363823e6e791e5}, // d=80: K(703), K(639)
	{0x3c255f5ebc414423, 0x34f5a24e22d66e90}, // d=96: K(831), K(767)
	{0xd083dd594d96319d, 0x946588403d4adcbc}, // d=112: K(959), K(895)
	{0xa1ca681e733f9c40, 0x5f852fb61e8d92dc}, // d=128: K(1087), K(1023)
	{0xcd72351bf13cb8ca, 0x3bee332187cc60f7}, // d=144: K(1215), K(1151)
	{0xb0fffabea073832e, 0x66650420c4bfb826}, // d=160: K(1343), K(1279)
	{0xee25ff27102e240d, 0xf62e65588693c72c}, // d=176: K(1471), K(1407)
	{0x758ee09da263e275, 0x6d2d13de8038b4ca}, // d=192: K(1599), K(1535)
	{0x3872b6300d5e5d6f, 0xba7a3407e09207aa}, // d=208: K(1727), K(1663)
	{0x3f2930bb5e9d61c5, 0x0d1476de2f12000f}, // d=224: K(1855), K(1791)
	{0xeab05d4357a9b42f, 0x224f0e5bd4980292}, // d=240: K(1983), K(1919)
	{0x37ccd3e14069cabc, 0xa043808c0f782663}, // d=256: K(2111), K(2047)
	{0xf6865e6e09336523, 0xaf2157ca1ac6c761}, // d=272: K(2239), K(2175)
	{0x0091c92c3c944810, 0x5e44c93e98d82108}, // d=288: K(2367), K(2303)
	{0x38f659a9d21de14a, 0xcd61588879b9fe22}, // d=304: K(2495), K(2431)
	{0x5b490ed66bc7198e, 0x98a3c6207ae8373d}, // d=320: K(2623), K(2559)
	{0xa4341ea70754fc16, 0x126dd5afb52f9ce4}, // d=336: K(2751), K(2687)
	{0xedf822c4d63c7728, 0xf03ca4363ad77178}, // d=352: K(2879), K(2815)
	{0xa0092bf548bf79d2, 0x215911d11dedbbd6}, // d=368: K(3007), K(2943)
	{0x6060c38d609f3e21, 0x5bdde9caef18f985}, // d=384: K(3135), K(3071)
	{0xb93e41242302a0d8, 0xb9d1ad02e7bdd4b0}, // d=400: K(3263), K(3199)
	{0xa654dc54e255bc86, 0x1c62cd4677a2190e}, // d=416: K(3391), K(3327)
	{0xda36257a1d6c477e, 0x593a983603eace9e}, // d=432: K(3519), K(3455)
	{0x7e6341dda0383248, 0xb06a02f5c37fb81b}, // d=448: K(3647), K(3583)
	{0x1f85eb5daa03dbb9, 0x6860ffa989545195}, // d=464: K(3775), K(3711)
	{0xaca27b938764b188, 0x24ea4e54779b35b9}, // d=480: K(3903), K(3839)
	{0x63fae1b85959c61f, 0x4fc3a895085a0b72}, // d=496: K(4031), K(3967)
	{0xd0b3aa0ed6d54ae0, 0xc2409e2537aa5eb1}, // d=512: K(4159), K(4095)
}

var byExp = map[int]uint64{
	127:  0x21e9761e252621ac,
	191:  0xeadc41fd2ba3d420,
	255:  0xe1e0bb9d45d7a44c,
	319:  0xb0bc2e589204f500,
	383:  0xa3ffdc1fe8e82a8b,
	447:  0xbdd7ac0ee1a4a0f0,
	511:  0x62242240ace5045a,
	575:  0x0c32cdb31e18a84a,
	639:  0x03363823e6e791e5,
	703:  0x7b0ab10dd0f809fe,
	767:  0x34f5a24e22d66e90,
	831:  0x3c255f5ebc414423,
	895:  0x946588403d4adcbc,
	959:  0xd083dd594d96319d,
	1023: 0x5f852fb61e8d92dc,
	1087: 0xa1ca681e733f9c40,
	1151: 0x3bee332187cc60f7,
	1215: 0xcd72351bf13cb8ca,
	1279: 0x66650420c4bfb826,
	1343: 0xb0fffabea073832e,
	1407: 0xf62e65588693c72c,
	1471: 0xee25ff27102e240d,
	1535: 0x6d2d13de8038b4ca,
	1599: 0x758ee09da263e275,
	1663: 0xba7a3407e09207aa,
	1727: 0x3872b6300d5e5d6f,
	1791: 0x0d1476de2f12000f,
	1855: 0x3f2930bb5e9d61c5,
	1919: 0x224f0e5bd4980292,
	1983: 0xeab05d4357a9b42f,
	2047: 0xa043808c0f782663,
	2111: 0x37ccd3e14069cabc,
	2175: 0xaf2157ca1ac6c761,
	2239: 0xf6865e6e09336523,
	2303: 0x5e44c93e98d82108,
	2367: 0x0091c92c3c944810,
	2431: 0xcd61588879b9fe22,
	2495: 0x38f659a9d21de14a,
	2559: 0x98a3c6207ae8373d,
	2623: 0x5b490ed66bc7198e,
	2687: 0x126dd5afb52f9ce4,
	2751: 0xa4341ea70754fc16,
	2815: 0xf03ca4363ad77178,
	2879: 0xedf822c4d63c7728,
	2943: 0x215911d11dedbbd6,
	3007: 0xa0092bf548bf79d2,
	3071: 0x5bdde9caef18f985,
	3135: 0x6060c38d609f3e21,
	3199: 0xb9d1ad02e7bdd4b0,
	3263: 0xb93e41242302a0d8,
	3327: 0x1c62cd4677a2190e,
	3391: 0xa654dc54e255bc86,
	3455: 0x593a983603eace9e,
	3519: 0xda36257a1d6c477e,
	3583: 0xb06a02f5c37fb81b,
	3647: 0x7e6341dda0383248,
	3711: 0x6860ffa989545195,
	3775: 0x1f85eb5daa03dbb9,
	3839: 0x24ea4e54779b35b9,
	3903: 0xaca27b938764b188,
	3967: 0x4fc3a895085a0b72,
	4031: 0x63fae1b85959c61f,
	4095: 0xc2409e2537aa5eb1,
	4159: 0xd0b3aa0ed6d54ae0,
}

// K returns bitrev64(x^e mod P) if e was emitted.
func K(e int) (uint64, bool) {
	v, ok := byExp[e]
	return v, ok
}
